
package es.unican.ss.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ConsultaAutobusesService", targetNamespace = "http://business.ss.unican.es/", wsdlLocation = "http://localhost:8080/Practica3/ConsultaAutobuses?wsdl")
public class ConsultaAutobusesService
    extends Service
{

    private final static URL CONSULTAAUTOBUSESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAAUTOBUSESSERVICE_EXCEPTION;
    private final static QName CONSULTAAUTOBUSESSERVICE_QNAME = new QName("http://business.ss.unican.es/", "ConsultaAutobusesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Practica3/ConsultaAutobuses?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAAUTOBUSESSERVICE_WSDL_LOCATION = url;
        CONSULTAAUTOBUSESSERVICE_EXCEPTION = e;
    }

    public ConsultaAutobusesService() {
        super(__getWsdlLocation(), CONSULTAAUTOBUSESSERVICE_QNAME);
    }

    public ConsultaAutobusesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAAUTOBUSESSERVICE_QNAME, features);
    }

    public ConsultaAutobusesService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAAUTOBUSESSERVICE_QNAME);
    }

    public ConsultaAutobusesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAAUTOBUSESSERVICE_QNAME, features);
    }

    public ConsultaAutobusesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaAutobusesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IConsultaAutobuses
     */
    @WebEndpoint(name = "ConsultaAutobusesPort")
    public IConsultaAutobuses getConsultaAutobusesPort() {
        return super.getPort(new QName("http://business.ss.unican.es/", "ConsultaAutobusesPort"), IConsultaAutobuses.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IConsultaAutobuses
     */
    @WebEndpoint(name = "ConsultaAutobusesPort")
    public IConsultaAutobuses getConsultaAutobusesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business.ss.unican.es/", "ConsultaAutobusesPort"), IConsultaAutobuses.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAAUTOBUSESSERVICE_EXCEPTION!= null) {
            throw CONSULTAAUTOBUSESSERVICE_EXCEPTION;
        }
        return CONSULTAAUTOBUSESSERVICE_WSDL_LOCATION;
    }

}
