
package es.unican.ss.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "DatosNoDisponibles", targetNamespace = "http://business.ss.unican.es/")
public class DatosNoDisponibles_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DatosNoDisponibles faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DatosNoDisponibles_Exception(String message, DatosNoDisponibles faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DatosNoDisponibles_Exception(String message, DatosNoDisponibles faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.unican.ss.client.DatosNoDisponibles
     */
    public DatosNoDisponibles getFaultInfo() {
        return faultInfo;
    }

}
