
package es.unican.ss.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IConsultaAutobuses", targetNamespace = "http://business.ss.unican.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IConsultaAutobuses {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws ParadaNoValida_Exception
     * @throws DatosNoDisponibles_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTUS", targetNamespace = "http://business.ss.unican.es/", className = "es.unican.ss.client.ConsultaTUS")
    @ResponseWrapper(localName = "consultaTUSResponse", targetNamespace = "http://business.ss.unican.es/", className = "es.unican.ss.client.ConsultaTUSResponse")
    @Action(input = "http://business.ss.unican.es/IConsultaAutobuses/consultaTUSRequest", output = "http://business.ss.unican.es/IConsultaAutobuses/consultaTUSResponse", fault = {
        @FaultAction(className = DatosNoDisponibles_Exception.class, value = "http://business.ss.unican.es/IConsultaAutobuses/consultaTUS/Fault/DatosNoDisponibles"),
        @FaultAction(className = ParadaNoValida_Exception.class, value = "http://business.ss.unican.es/IConsultaAutobuses/consultaTUS/Fault/ParadaNoValida")
    })
    public List<Object> consultaTUS(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws DatosNoDisponibles_Exception, ParadaNoValida_Exception
    ;

}
